volumes:
  pg_data_production:
    name: pg_data_production
  static_volume:
    name: static_volume
  
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: yanakuzya/taski_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
  frontend:
    env_file: .env
    image: yanakuzya/taski_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: yanakuzya/taski_gateway
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - backend